# Generated by Django 3.1 on 2020-10-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20201019_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owm_id', models.IntegerField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('utc_offset', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_time', models.DateTimeField()),
                ('last_update_time', models.DateTimeField()),
                ('reception_time', models.DateTimeField()),
                ('location_id', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('rain', models.DecimalField(decimal_places=2, max_digits=2)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=2)),
                ('wind', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.CharField(max_length=3000),
        ),
    ]
