# Generated by Django 3.1 on 2020-10-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20201020_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='moisture_threshold',
        ),
        migrations.RemoveField(
            model_name='valve',
            name='valve_threshold',
        ),
        migrations.AddField(
            model_name='plan',
            name='moisture_threshold',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='plan',
            name='valve_threshold',
            field=models.IntegerField(default=100),
        ),
    ]
