# Generated by Django 3.1 on 2020-10-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20201022_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_active_plan',
            field=models.BooleanField(default=False),
        ),
    ]
