# Generated by Django 3.1 on 2020-10-22 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20201022_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='weather_status_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.weatherstatus'),
            preserve_default=False,
        ),
    ]
