# Generated by Django 3.1.1 on 2020-10-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_weatherdata_weather_status_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='automation_temperature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='valve',
            name='watering_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
