# Generated by Django 3.1 on 2020-10-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20201023_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='valve',
            name='valve_counter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='weathercounter',
            name='weather_counter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
