# Generated by Django 3.1 on 2020-10-23 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20201023_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valve',
            name='sensor_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.sensor'),
        ),
    ]
