# Generated by Django 3.1 on 2020-10-25 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_auto_20201023_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='WateringStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valve_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.valve')),
            ],
        ),
    ]
