# Generated by Django 3.1 on 2020-10-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_wateringstatistic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='allow_friday',
            new_name='friday',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='allow_monday',
            new_name='monday',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='allow_saturday',
            new_name='saturday',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='allow_sunday',
            new_name='sunday',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='allow_thursday',
            new_name='thursday',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='allow_time_start',
            new_name='time_start',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='allow_time_stop',
            new_name='time_stop',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='allow_tuesday',
            new_name='tuesday',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='allow_wednesday',
            new_name='wednesday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='deny_friday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='deny_monday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='deny_saturday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='deny_sunday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='deny_thursday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='deny_time_start',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='deny_time_stop',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='deny_tuesday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='deny_wednesday',
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_allow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_deny',
            field=models.BooleanField(default=False),
        ),
    ]
