# Generated by Django 3.1 on 2020-10-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_auto_20201025_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wateringstatistic',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
