# Generated by Django 3.1 on 2020-10-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_auto_20201025_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateringstatistic',
            name='water_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
