# Generated by Django 3.1 on 2020-10-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_wateringstatistic_water_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='moisture',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
