# Generated by Django 3.1 on 2020-10-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_sensor_moisture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owm_api_key', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='plan',
            name='moisture_threshold',
            field=models.DecimalField(decimal_places=2, default=55, max_digits=5),
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
